### ISSUE TITLE
No tenantId

### ISSUE THREAD

**Issue by tpharaoh** [HipsterJazzbo/Landlord#19]
I added Landlord::addTenant($tenantColumn, $tenantId) to the Authenticate middleware, since I wanted this on every authenticated page.

I get: Undefined variable: tenantColumn

**Comment by cargie** [comment]
$company = Company::first();
Landlord::addTenant('company_id', $company->id);

**Comment by dschallert** [comment]
Hi, 

could you may share your middleware code? 

I'm facing the same issue..

Thanks

**Comment by cargie** [comment]
its very simple ones you understand it.
its how it works.

ones you put Landlord::addTenant('company_id', 1);

all eloquent queries under that middleware will automatically add
where('company_id',1) on your eloquent.

say you want to query customers.

Customer::get();

since your adding landlord on your middleware, your query will now be like
this under the hood.
Customer::where('company_id',1)->get(); so all your queries under the
landlord middleware will be scoped globally.
